{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
{{ end }}