apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netol-role
  namespace: default
subjects:
- kind: User
  name: netol
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: netol-role
  apiGroup: rbac.authorization.k8s.io