apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1-pvc
  namespace: default
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

