apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  type: NodePort
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  - name: multi
    port: 9002
    protocol: TCP
    targetPort: 8080
    nodePort: 30002
  selector:
    app: nginx