apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
  - name: multi
    port: 9002
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx