apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-nginx
  annotations: 
    kubernetes.io/change-cause: "Update to 1.28"
  labels:
    app: multi-nginx
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 80%
  selector:
    matchLabels:
      app: multi-nginx
  template:
    metadata:
      labels:
        app: multi-nginx
    spec:
      containers:
      - name: wbitt
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT 
          value: "8443"
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx:1.28
        ports:
        - containerPort: 80
