apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multi
  labels:
    app: multi
spec:
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - name: wbitt
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT 
          value: "8443"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vol1
          mountPath: /input
      volumes: 
      - name: vol1  
        hostPath: 
          path: /var/log