
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 8080; # Define the port here
            server_name localhost;

            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>My Nginx Website</title>
    </head>
    <body>
    <h1>Welcome to My ConfigMap Website!</h1>
    <p>This is may be the default index.html page served by Nginx.</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf 
          subPath: nginx.conf 
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html/index.html 
          subPath: index.html 
      - name: wbitt
        image: wbitt/network-multitool
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-custom-config
